fix: :bug: latest scripts to generate changelog copied to repository

diff --git a/tekton/task_generate_changelog/task_generate_changelog.yml b/tekton/task_generate_changelog/task_generate_changelog.yml
--- a/tekton/task_generate_changelog/task_generate_changelog.yml
+++ b/tekton/task_generate_changelog/task_generate_changelog.yml
@@ -1,116 +1,183 @@
-#!/bin/sh
+apiVersion: tekton.dev/v1beta1
+kind: Task
+metadata:
+  name: generate-changelog
+  labels:
+    app.kubernetes.io/version: "0.1"
+  annotations:
+    tekton.dev/pipelines.minVersion: "0.12.1"
+    tekton.dev/categories: Publishing
+    tekton.dev/tags: documentation
+    tekton.dev/platforms: "linux/amd64"
+spec:
+  description: >-
+    Task to generate a build tag
+  workspaces:
+    - name: source
+  results:
+  - name: changelog-file-path
+    description: file path of the changelog file
+  params:
+  - name: changelog-file-name
+    type: string
+    description: file name of the changelog file
+    default: "CHANGELOG.md"
+  steps:
+    - name: generate-changelog
+      image: quay.io/michard/tekton_base_image:0.1.10
+      script: |
+        #!/bin/sh
+        # Exit on error
+        set -e
 
-# Exit on error
-set -e
+        # Error handling
+        trap 'echo "An error occurred at line $LINENO. Exiting."' ERR
 
-# Error handling
-trap 'echo "An error occurred at line $LINENO. Exiting."' ERR
+        # Path to the Git repository (current directory)
+        REPO_DIR="/workspace/source"
+        CHANGELOG_FILE="$REPO_DIR/$(params.changelog-file-name)"
+         
+        # save changelog file path to results variable
+        echo ${CHANGELOG_FILE} | tr -d "\n" | tee $(results.changelog-file-path.path)
 
-# Path to the Git repository (current directory)
-REPO_DIR="."
-CHANGELOG_FILE="$REPO_DIR/CHANGELOG.md"
-GITHUB_REPO_URL=$(git remote get-url origin | sed 's/\.git$//') # get repository url from git remote
+        echo -e "\nStarting changelog generation script..."
+        git config --global --add safe.directory /workspace/source
+        git -C /workspace/source fetch --unshallow
 
-echo "Starting changelog generation script..."
-echo "Repository:"
-echo $GITHUB_REPO_URL
-# Create or clear the changelog file
-> $CHANGELOG_FILE
+        # Create or clear the changelog file
+        > $CHANGELOG_FILE
 
-# Add the introductory text to the changelog
-echo "# Changelog" >> $CHANGELOG_FILE
-echo "" >> $CHANGELOG_FILE
-echo "All notable changes to this project will be documented in this file." >> $CHANGELOG_FILE
-echo "" >> $CHANGELOG_FILE
-echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) and to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)." >> $CHANGELOG_FILE
-echo "" >> $CHANGELOG_FILE
-
-# Go to the repository directory
-cd $REPO_DIR
-
-# Fetch the latest changes
-git fetch --tags
-echo "Fetched latest tags."
-
-# Get the latest tag
-LATEST_TAG=$(git describe --tags --abbrev=0)
-
-# Get tags in reverse order
-TAGS=$(git tag --sort=-v:refname)
-
-# Check if there are any tags
-if [ -z "$TAGS" ]; then
-    echo "No tags found in the repository."
-    exit 1
-fi
-
-echo "Found tags: $TAGS"
-
-# Placeholder for the previous tag
-PREV_TAG=HEAD
-
-# Define categories
-CATEGORIES="feat fix ci perf docs gitops deploy test demo build chore style refactor"
-
-# Regular expression for matching conventional commits
-CONVENTIONAL_COMMIT_REGEX="^.* (feat|fix|ci|perf|docs|gitops|deploy|test|demo|build|chore|style|refactor)(\(.*\))?: "
-
-# Iterate over tags
-for TAG in $TAGS; do
-    echo "Processing tag: $TAG"
-    TAG_DATE=$(git log -1 --format=%ai $TAG | cut -d ' ' -f 1)
-    echo "## $TAG ($TAG_DATE)" >> $CHANGELOG_FILE
-    echo "" >> $CHANGELOG_FILE
-
-    # Collect all commits for this tag range
-    ALL_COMMITS=$(git log $TAG..$PREV_TAG --oneline --always)
-
-    # Process each category
-    for KEY in $CATEGORIES; do
-        CATEGORY_COMMITS=$(echo "$ALL_COMMITS" | grep -E "^.* $KEY(\(.*\))?: " || true)
-        if [ ! -z "$CATEGORY_COMMITS" ]; then
-            case $KEY in
-                "feat") CATEGORY_NAME="Feature" ;;
-                "fix") CATEGORY_NAME="Bug Fixes" ;;
-                "ci") CATEGORY_NAME="Continuous Integration" ;;
-                "perf") CATEGORY_NAME="Performance Improvements" ;;
-                "docs") CATEGORY_NAME="Documentation" ;;
-                "gitops") CATEGORY_NAME="GitOps" ;;
-                "deploy") CATEGORY_NAME="Deployment" ;;
-                "test") CATEGORY_NAME="Test" ;;
-                "demo") CATEGORY_NAME="Demo" ;;
-                "build") CATEGORY_NAME="Build" ;;
-                "chore") CATEGORY_NAME="Chore" ;;
-                "style") CATEGORY_NAME="Style" ;;
-                "refactor") CATEGORY_NAME="Refactor" ;;
-            esac
-            echo "### $CATEGORY_NAME" >> $CHANGELOG_FILE
-            echo "Listing commits for category: $CATEGORY_NAME under tag $TAG"
-            echo "$CATEGORY_COMMITS" | while read -r COMMIT; do
-                HASH=$(echo $COMMIT | awk '{print $1}')
-                MESSAGE=$(echo $COMMIT | sed -E "s/^$HASH $KEY(\(.*\))?: //")
-                echo "- $MESSAGE [\`$HASH\`]($GITHUB_REPO_URL/commit/$HASH)" >> $CHANGELOG_FILE
-            done
-            echo "" >> $CHANGELOG_FILE
-        fi
-    done
-
-    # Process 'Other' category
-    OTHER_COMMITS=$(echo "$ALL_COMMITS" | grep -v -E "$CONVENTIONAL_COMMIT_REGEX" || true)
-    if [ ! -z "$OTHER_COMMITS" ]; then
-        echo "### Other" >> $CHANGELOG_FILE
-        echo "Listing commits for category: Other under tag $TAG"
-        echo "$OTHER_COMMITS" | while read -r COMMIT; do
-            HASH=$(echo $COMMIT | awk '{print $1}')
-            MESSAGE=$(echo $COMMIT | sed -E 's/^[^ ]* //')
-            echo "- $MESSAGE [\`$HASH\`]($GITHUB_REPO_URL/commit/$HASH)" >> $CHANGELOG_FILE
-        done
+        # Add the introductory text to the changelog
+        echo "# Changelog" >> $CHANGELOG_FILE
         echo "" >> $CHANGELOG_FILE
-    fi
+        echo "All notable changes to this project will be documented in this file." >> $CHANGELOG_FILE
+        echo "" >> $CHANGELOG_FILE
+        echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) and to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)." >> $CHANGELOG_FILE
+        echo "" >> $CHANGELOG_FILE
 
-    echo "Completed processing tag: $TAG"
-    # Update the previous tag
-    PREV_TAG=$TAG
-done
+        # Go to the repository directory
+        cd $REPO_DIR
 
-echo "Changelog generation complete."
+        # Get repository url
+        GITHUB_REPO_URL=$(git remote get-url origin 2>/dev/null | sed 's/\.git$//')
+        if [ -z "$GITHUB_REPO_URL" ]; then
+            GITHUB_REPO_URL=0
+        fi
+
+        echo "Repository:"
+        echo $GITHUB_REPO_URL
+
+        # Fetch the latest changes
+        git fetch --tags
+        echo "Fetched latest tags."
+
+        # Get the latest tag
+        LATEST_TAG=$(git describe --tags --abbrev=0)
+
+        # Get tags in reverse order
+        TAGS=$(git tag --sort=-v:refname)
+
+        # Check if there are any tags
+        if [ -z "$TAGS" ]; then
+            echo "No tags found in the repository."
+            exit 1
+        fi
+
+        echo "Found tags: $TAGS"
+
+        # Placeholder for the previous tag
+        TAG_TO=HEAD
+
+        # Define categories
+        CATEGORIES="feat fix ci perf docs gitops deploy test demo build chore style refactor"
+
+        # Regular expression for matching conventional commits
+        CONVENTIONAL_COMMIT_REGEX="^.* (feat|fix|ci|perf|docs|gitops|deploy|test|demo|build|chore|style|refactor)(\(.*\))?: "
+
+        print_tag() {
+            echo "Processing tag: $2"
+            TAG_DATE=$(git log -1 --format=%ai $2 | cut -d ' ' -f 1)
+            if [ "$2" = "HEAD" ]; then
+                if [ $(git rev-parse $1) != $(git rev-parse "HEAD") ]; then
+                    echo "## Unreleased changes" >> $CHANGELOG_FILE
+                    echo "" >> $CHANGELOG_FILE
+                fi
+            else
+                echo "## $2 ($TAG_DATE)" >> $CHANGELOG_FILE
+                echo "" >> $CHANGELOG_FILE
+            fi
+            
+
+            # Collect all commits for this tag range
+            if [ -z "$1" ]; then
+                ALL_COMMITS=$(git log $2 --oneline --always)
+            else
+                ALL_COMMITS=$(git log $1..$2 --oneline --always)
+            fi
+
+            # Process each category
+            for KEY in $CATEGORIES; do
+                CATEGORY_COMMITS=$(echo "$ALL_COMMITS" | grep -E "^.* $KEY(\(.*\))?: " || true)
+                if [ ! -z "$CATEGORY_COMMITS" ]; then
+                    case $KEY in
+                        "feat") CATEGORY_NAME="Feature" ;;
+                        "fix") CATEGORY_NAME="Bug Fixes" ;;
+                        "ci") CATEGORY_NAME="Continuous Integration" ;;
+                        "perf") CATEGORY_NAME="Performance Improvements" ;;
+                        "docs") CATEGORY_NAME="Documentation" ;;
+                        "gitops") CATEGORY_NAME="GitOps" ;;
+                        "deploy") CATEGORY_NAME="Deployment" ;;
+                        "test") CATEGORY_NAME="Test" ;;
+                        "demo") CATEGORY_NAME="Demo" ;;
+                        "build") CATEGORY_NAME="Build" ;;
+                        "chore") CATEGORY_NAME="Chore" ;;
+                        "style") CATEGORY_NAME="Style" ;;
+                        "refactor") CATEGORY_NAME="Refactor" ;;
+                    esac
+                    echo "### $CATEGORY_NAME" >> $CHANGELOG_FILE
+                    echo "Listing commits for category: $CATEGORY_NAME under tag $2"
+                    echo "$CATEGORY_COMMITS" | while read -r COMMIT; do
+                        HASH=$(echo $COMMIT | awk '{print $1}')
+                        MESSAGE=$(echo $COMMIT | sed -E "s/^$HASH $KEY(\(.*\))?: //")
+                        if [ "$GITHUB_REPO_URL" != "0" ]; then
+                            echo "- $MESSAGE [\`$HASH\`]($GITHUB_REPO_URL/commit/$HASH)" >> $CHANGELOG_FILE
+                        else
+                            echo "- $MESSAGE" >> $CHANGELOG_FILE
+                        fi
+                    done
+                    echo "" >> $CHANGELOG_FILE
+                fi
+            done
+
+            # Process 'Other' category
+            OTHER_COMMITS=$(echo "$ALL_COMMITS" | grep -v -E "$CONVENTIONAL_COMMIT_REGEX" || true)
+            if [ ! -z "$OTHER_COMMITS" ]; then
+                echo "### Other" >> $CHANGELOG_FILE
+                echo "Listing commits for category: Other under tag $2"
+                echo "$OTHER_COMMITS" | while read -r COMMIT; do
+                    HASH=$(echo $COMMIT | awk '{print $1}')
+                    MESSAGE=$(echo $COMMIT | sed -E 's/^[^ ]* //')
+                    if [ "$GITHUB_REPO_URL" != "0" ]; then
+                        echo "- $MESSAGE [\`$HASH\`]($GITHUB_REPO_URL/commit/$HASH)" >> $CHANGELOG_FILE
+                    else
+                        echo "- $MESSAGE" >> $CHANGELOG_FILE
+                    fi
+                done
+                echo "" >> $CHANGELOG_FILE
+            fi
+
+            echo "Completed processing tag: $2"
+            # Update the previous tag
+        }
+
+        # Iterate over tags
+        for TAG_FROM in $TAGS; do
+            print_tag $TAG_FROM $TAG_TO
+            TAG_TO=$TAG_FROM
+        done
+        print_tag "" $TAG_FROM
+
+        echo "Changelog generation complete."
+
+        echo "Content of the Changelog file:"
+        cat CHANGELOG.md
